### ISSUE TITLE
New Pressure Bands

### ISSUE THREAD

**Issue by Muirrum** [WPI-LNL/hp#15]

**Comment by Simulatedbog545** [comment]
Asked Sean to get us a price, exact number tbd.

**Comment by Muirrum** [comment]
Received quote, asking for exec/club approval tonight

**Comment by Simulatedbog545** [comment]
After personally sorting through BLS' stock of pressure bands, almost all of them are fucked in some way; gashes, scorch marks, or chunks missing. We should still investigate getting a bunch made. Apparently BLS tried a while ago and did not get satisfactory results, hence the stockpile only having old used ones.

**Comment by Simulatedbog545** [comment]
Delivered to the booth. In small boxes on a ziplock bag on the bench
