### ISSUE TITLE
DP70 VFD

### ISSUE THREAD

**Issue by Muirrum** [WPI-LNL/hp#3]

**Comment by Muirrum** [comment]
parts ordered, waiting on shipping

**Comment by Simulatedbog545** [comment]
Parts arrived and inspected. Pending install scheduled for weekend of 5-27-23

**Comment by Simulatedbog545** [comment]
P2 Completed!

**Comment by Simulatedbog545** [comment]
DONE! P1 was completed yesterday, I just forgot to update this. *oops*
